//go:build dbox2d_fixed

// Code generated by tools/q32gen from contact_solver.go; DO NOT EDIT.

package dbox2d

// contact separation for sub-stepping
// s = s0 + dot(cB + rB - cA - rA, normal)
// normal is held constant
// body positions c can translation and anchors r can rotate
// s(t) = s0 + dot(cB(t) + rB(t) - cA(t) - rA(t), normal)
// s(t) = s0 + dot(cB0 + dpB + rot(dqB, rB0) - cA0 - dpA - rot(dqA, rA0), normal)
// s(t) = s0 + dot(cB0 - cA0, normal) + dot(dpB - dpA + rot(dqB, rB0) - rot(dqA, rA0), normal)
// s_base = s0 + dot(cB0 - cA0, normal)

// contactConstraintPoint32 is the solver view of one manifold point. It
// corresponds to b2ContactConstraintPoint in src/contact_solver.h.
type contactConstraintPoint32 struct {
	anchorA, anchorB   vec2cw
	baseSeparation     qcw
	relativeVelocity   qcw
	normalImpulse      qcw
	tangentImpulse     qcw
	totalNormalImpulse qaw
	normalMass         qcw
	tangentMass        qcw
}

// contactConstraint32 is the solver view of one touching contact. It
// corresponds to b2ContactConstraint in src/contact_solver.h.
type contactConstraint32 struct {
	indexA             int
	indexB             int
	points             [2]contactConstraintPoint32
	normal             vec2cw
	invMassA, invMassB qcw
	invIA, invIB       qcw
	friction           qcw
	restitution        qcw
	tangentSpeed       qcw
	rollingResistance  qcw
	rollingMass        qcw
	rollingImpulse     qcw
	softness           contactSoft32
	pointCount         int
}

// contactSoft32 is a softness on the contact grid.
type contactSoft32 struct {
	biasRate, massScale, impulseScale qcw
}

func contactSoftFrom32(s softness) contactSoft32 {
	return contactSoft32{biasRate: qcwFrom(s.biasRate), massScale: qcwFrom(s.massScale), impulseScale: qcwFrom(s.impulseScale)}
}

// The prepare stage computes in Q and rounds each result to the contact
// grid. The other stages compute on the grid and accumulate the body
// velocities and the total normal impulse in qaw: the same grid with more
// integer range, so a sum does not saturate.

// D-004: the body state keeps the angular velocity in turns per second.
// The solver works in radians per second, so each stage scales the
// velocity by one turn on load and divides by one turn on store.

// contactBody32 is the velocity of one body while a stage solves a contact.
type contactBody32 struct {
	vx, vy, w qaw
}

func loadContactBody32(state *bodyState) contactBody32 {
	return contactBody32{
		vx: qawFrom(state.linearVelocity.X),
		vy: qawFrom(state.linearVelocity.Y),
		w:  qawFrom(state.angularVelocity.Mul(tau)),
	}
}

func (b *contactBody32) store(state *bodyState) {
	state.linearVelocity = Vec2{X: b.vx.toQ(), Y: b.vy.toQ()}
	state.angularVelocity = b.w.toQ().Div(tau)
}

// velocityAt returns the velocity of the body at the anchor r.
func (b *contactBody32) velocityAt(r vec2cw) vec2cw {
	w := b.w.narrow()
	return vec2cw{X: b.vx.narrow().Add(w.Neg().Mul(r.Y)), Y: b.vy.narrow().Add(w.Mul(r.X))}
}

// applyContactImpulse32 applies the impulse p at the anchors rA and rB.
func applyContactImpulse32(bodyA, bodyB *contactBody32, constraint *contactConstraint32, rA, rB, p vec2cw) {
	bodyA.vx = bodyA.vx.Sub(constraint.invMassA.Mul(p.X).widen())
	bodyA.vy = bodyA.vy.Sub(constraint.invMassA.Mul(p.Y).widen())
	bodyA.w = bodyA.w.Sub(constraint.invIA.Mul(crossc32(rA, p)).widen())
	bodyB.vx = bodyB.vx.Add(constraint.invMassB.Mul(p.X).widen())
	bodyB.vy = bodyB.vy.Add(constraint.invMassB.Mul(p.Y).widen())
	bodyB.w = bodyB.w.Add(constraint.invIB.Mul(crossc32(rB, p)).widen())
}

func vec2cFrom32(v Vec2) vec2cw { return vec2cw{X: qcwFrom(v.X), Y: qcwFrom(v.Y)} }

func rotcFrom32(r Rot) rotcw { return rotcw{Sin: qcwFrom(r.Sin), Cos: qcwFrom(r.Cos)} }

func crossc32(a, b vec2cw) qcw { return a.X.Mul(b.Y).Sub(a.Y.Mul(b.X)) }

// The scalar family serves every color. Contacts of one active color share
// no dynamic body, while overflow stages remain whole-color operations. The
// overflow stages also run the Q32 tail of their color; the active colors
// run theirs as the last unit of the color (runGraphContactBlock).

func prepareContactRange32(startIndex, endIndex int, context *stepContext, contacts []*contactSim, constraints []contactConstraint32) {
	w := context.world
	awakeStates := context.states
	constraints = constraints[startIndex:endIndex]
	contacts = contacts[startIndex:endIndex]

	// Stiffer for static contacts to avoid bodies getting pushed through the ground
	contactSoftness := contactSoftFrom32(context.contactSoftness)
	staticSoftness := contactSoftFrom32(context.staticSoftness)

	zero := QZero()
	one := QOne()
	warmStartScale := zero
	if w.enableWarmStarting {
		warmStartScale = one
	}

	for i := range endIndex - startIndex {
		cs := contacts[i]
		manifold := &cs.manifold
		pointCount := manifold.PointCount

		if pointCount <= 0 || pointCount > 2 {
			panic("dbox2d: the manifold point count is out of range")
		}

		indexA := cs.bodySimIndexA
		indexB := cs.bodySimIndexB

		constraint := &constraints[i]
		constraint.indexA = indexA
		constraint.indexB = indexB
		constraint.normal = vec2cFrom32(manifold.Normal)
		constraint.friction = qcwFrom(cs.friction)
		constraint.restitution = qcwFrom(cs.restitution)
		constraint.rollingResistance = qcwFrom(cs.rollingResistance)
		constraint.rollingImpulse = qcwFrom(warmStartScale.Mul(manifold.RollingImpulse))
		constraint.tangentSpeed = qcwFrom(cs.tangentSpeed)
		constraint.pointCount = pointCount

		vA := Vec2Zero()
		wA := zero
		mA := cs.invMassA
		iA := cs.invIA
		if indexA != nullIndex {
			stateA := &awakeStates[indexA]
			vA = stateA.linearVelocity
			wA = stateA.angularVelocity.Mul(tau)
		}

		vB := Vec2Zero()
		wB := zero
		mB := cs.invMassB
		iB := cs.invIB
		if indexB != nullIndex {
			stateB := &awakeStates[indexB]
			vB = stateB.linearVelocity
			wB = stateB.angularVelocity.Mul(tau)
		}

		if indexA == nullIndex || indexB == nullIndex {
			constraint.softness = staticSoftness
		} else {
			constraint.softness = contactSoftness
		}

		// copy mass into constraint to avoid cache misses during sub-stepping
		constraint.invMassA = qcwFrom(mA)
		constraint.invIA = qcwFrom(iA)
		constraint.invMassB = qcwFrom(mB)
		constraint.invIB = qcwFrom(iB)

		// D-006: the effective masses store the reciprocal once, as the
		// inverse mass of a body does.
		{
			k := iA.Add(iB)
			constraint.rollingMass = qcw{}
			if zero.Less(k) {
				constraint.rollingMass = qcwFrom(one.Div(k))
			}
		}

		normal := manifold.Normal
		tangent := RightPerp(normal)

		for j := range pointCount {
			mp := &manifold.Points[j]
			cp := &constraint.points[j]

			cp.normalImpulse = qcwFrom(warmStartScale.Mul(mp.NormalImpulse))
			cp.tangentImpulse = qcwFrom(warmStartScale.Mul(mp.TangentImpulse))
			cp.totalNormalImpulse = qaw{}

			rA := mp.AnchorA
			rB := mp.AnchorB

			cp.anchorA = vec2cFrom32(rA)
			cp.anchorB = vec2cFrom32(rB)
			cp.baseSeparation = qcwFrom(mp.Separation.Sub(rB.Sub(rA).Dot(normal)))

			rnA := Cross(rA, normal)
			rnB := Cross(rB, normal)
			kNormal := mA.Add(mB).Add(iA.Mul(rnA).Mul(rnA)).Add(iB.Mul(rnB).Mul(rnB))
			cp.normalMass = qcw{}
			if zero.Less(kNormal) {
				cp.normalMass = qcwFrom(one.Div(kNormal))
			}

			rtA := Cross(rA, tangent)
			rtB := Cross(rB, tangent)
			kTangent := mA.Add(mB).Add(iA.Mul(rtA).Mul(rtA)).Add(iB.Mul(rtB).Mul(rtB))
			cp.tangentMass = qcw{}
			if zero.Less(kTangent) {
				cp.tangentMass = qcwFrom(one.Div(kTangent))
			}

			// Save relative velocity for restitution
			vrA := vA.Add(CrossSV(wA, rA))
			vrB := vB.Add(CrossSV(wB, rB))
			cp.relativeVelocity = qcwFrom(normal.Dot(vrB.Sub(vrA)))
		}
	}
}

// constraintStates32 returns the two body states of a constraint. A static
// side gets the dummy state, because static bodies have no solver body.
func constraintStates32(states []bodyState, dummy *bodyState, constraint *contactConstraint32) (stateA, stateB *bodyState) {
	stateA = dummy
	if constraint.indexA != nullIndex {
		stateA = &states[constraint.indexA]
	}
	stateB = dummy
	if constraint.indexB != nullIndex {
		stateB = &states[constraint.indexB]
	}
	return stateA, stateB
}

func warmStartContactRange32(startIndex, endIndex int, context *stepContext, constraints []contactConstraint32) {
	w := context.world
	awake := &w.solverSets[awakeSet]
	states := awake.bodyStates
	constraints = constraints[startIndex:endIndex]

	// This is a dummy state to represent a static body because static bodies don't have a solver body.
	dummyState := identityBodyState()

	for i := range endIndex - startIndex {
		constraint := &constraints[i]

		stateA, stateB := constraintStates32(states, &dummyState, constraint)
		bodyA := loadContactBody32(stateA)
		bodyB := loadContactBody32(stateB)

		// Stiffer for static contacts to avoid bodies getting pushed through the ground
		normal := constraint.normal
		tangent := vec2cw{X: normal.Y, Y: normal.X.Neg()}
		pointCount := constraint.pointCount

		for j := range pointCount {
			cp := &constraint.points[j]

			// fixed anchors
			rA := cp.anchorA
			rB := cp.anchorB

			P := normal.Mul(cp.normalImpulse).Add(tangent.Mul(cp.tangentImpulse))
			applyContactImpulse32(&bodyA, &bodyB, constraint, rA, rB, P)
		}

		bodyA.w = bodyA.w.Sub(constraint.invIA.Mul(constraint.rollingImpulse).widen())
		bodyB.w = bodyB.w.Add(constraint.invIB.Mul(constraint.rollingImpulse).widen())

		bodyA.store(stateA)
		bodyB.store(stateB)
	}
}

// Colored contacts clamp by the contact speed, per b2SolveContactsTask.

// Overflow contacts clamp by the push speed, per b2SolveOverflowContacts.

func solveContactRange32(startIndex, endIndex int, context *stepContext, constraints []contactConstraint32, useBias bool, pushout qcw) {
	w := context.world
	awake := &w.solverSets[awakeSet]
	states := awake.bodyStates
	constraints = constraints[startIndex:endIndex]

	invH := qcwFrom(context.invH)

	// This is a dummy body to represent a static body since static bodies don't have a solver body.
	dummyState := identityBodyState()

	zero := qcw{}
	one := qcwFrom(QOne())
	for i := range endIndex - startIndex {
		constraint := &constraints[i]

		stateA, stateB := constraintStates32(states, &dummyState, constraint)
		bodyA := loadContactBody32(stateA)
		dqA := rotcFrom32(stateA.deltaRotation)

		bodyB := loadContactBody32(stateB)
		dqB := rotcFrom32(stateB.deltaRotation)

		dp := vec2cFrom32(stateB.deltaPosition).Sub(vec2cFrom32(stateA.deltaPosition))

		normal := constraint.normal
		tangent := vec2cw{X: normal.Y, Y: normal.X.Neg()}
		friction := constraint.friction
		soft := constraint.softness

		pointCount := constraint.pointCount
		totalNormalImpulse := qaw{}

		// Non-penetration
		for j := range pointCount {
			cp := &constraint.points[j]

			// fixed anchor points
			rA := cp.anchorA
			rB := cp.anchorB

			// compute current separation
			// this is subject to round-off error if the anchor is far from the body center of mass
			ds := dp.Add(dqB.Apply(rB).Sub(dqA.Apply(rA)))
			s := cp.baseSeparation.Add(ds.Dot(normal))

			velocityBias := zero
			massScale := one
			impulseScale := zero
			if zero.Less(s) {
				// speculative bias
				velocityBias = s.Mul(invH)
			} else if useBias {
				velocityBias = soft.biasRate.Mul(s).Max(pushout.Neg())
				massScale = soft.massScale
				impulseScale = soft.impulseScale
			}

			// relative normal velocity at contact
			vn := bodyB.velocityAt(rB).Sub(bodyA.velocityAt(rA)).Dot(normal)

			// incremental normal impulse
			impulse := cp.normalMass.Neg().Mul(massScale).Mul(vn.Add(velocityBias)).Sub(impulseScale.Mul(cp.normalImpulse))

			// clamp the accumulated impulse
			newImpulse := cp.normalImpulse.Add(impulse).Max(zero)
			impulse = newImpulse.Sub(cp.normalImpulse)
			cp.normalImpulse = newImpulse
			cp.totalNormalImpulse = cp.totalNormalImpulse.Add(newImpulse.widen())
			totalNormalImpulse = totalNormalImpulse.Add(newImpulse.widen())

			// apply normal impulse
			applyContactImpulse32(&bodyA, &bodyB, constraint, rA, rB, normal.Mul(impulse))
		}

		// Friction
		for j := range pointCount {
			cp := &constraint.points[j]

			// fixed anchor points
			rA := cp.anchorA
			rB := cp.anchorB

			// relative tangent velocity at contact
			// vt = dot(vrB - sB * tangent - (vrA + sA * tangent), tangent)
			//    = dot(vrB - vrA, tangent) - (sA + sB)
			vt := bodyB.velocityAt(rB).Sub(bodyA.velocityAt(rA)).Dot(tangent).Sub(constraint.tangentSpeed)

			// incremental tangent impulse
			impulse := cp.tangentMass.Mul(vt.Neg())

			// clamp the accumulated force
			maxFriction := friction.Mul(cp.normalImpulse)
			newImpulse := cp.tangentImpulse.Add(impulse).Clamp(maxFriction.Neg(), maxFriction)
			impulse = newImpulse.Sub(cp.tangentImpulse)
			cp.tangentImpulse = newImpulse

			// apply tangent impulse
			applyContactImpulse32(&bodyA, &bodyB, constraint, rA, rB, tangent.Mul(impulse))
		}

		// Rolling resistance
		{
			deltaLambda := constraint.rollingMass.Neg().Mul(bodyB.w.Sub(bodyA.w).narrow())
			lambda := constraint.rollingImpulse
			maxLambda := rollingBound32(constraint.rollingResistance, totalNormalImpulse)
			constraint.rollingImpulse = lambda.Add(deltaLambda).Clamp(maxLambda.Neg(), maxLambda)
			deltaLambda = constraint.rollingImpulse.Sub(lambda)

			bodyA.w = bodyA.w.Sub(constraint.invIA.Mul(deltaLambda).widen())
			bodyB.w = bodyB.w.Add(constraint.invIB.Mul(deltaLambda).widen())
		}

		bodyA.store(stateA)
		bodyB.store(stateB)
	}
}

func applyRestitutionRange32(startIndex, endIndex int, context *stepContext, constraints []contactConstraint32) {
	w := context.world
	awake := &w.solverSets[awakeSet]
	states := awake.bodyStates
	constraints = constraints[startIndex:endIndex]

	threshold := qcwFrom(w.restitutionThreshold)

	// dummy state to represent a static body
	dummyState := identityBodyState()

	zero := qcw{}
	for i := range endIndex - startIndex {
		constraint := &constraints[i]

		restitution := constraint.restitution
		if restitution.Eq(zero) {
			continue
		}

		stateA, stateB := constraintStates32(states, &dummyState, constraint)
		bodyA := loadContactBody32(stateA)
		bodyB := loadContactBody32(stateB)

		normal := constraint.normal
		pointCount := constraint.pointCount

		// it is possible to get more accurate restitution by iterating
		// this only makes a difference if there are two contact points
		// for (int iter = 0; iter < 10; ++iter)
		{
			for j := range pointCount {
				cp := &constraint.points[j]

				// if the normal impulse is zero then there was no collision
				// this skips speculative contact points that didn't generate an impulse
				// The max normal impulse is used in case there was a collision that moved away within the sub-step process
				if threshold.Neg().Less(cp.relativeVelocity) || cp.totalNormalImpulse.Eq(qaw{}) {
					continue
				}

				// fixed anchor points
				rA := cp.anchorA
				rB := cp.anchorB

				// relative normal velocity at contact
				vn := bodyB.velocityAt(rB).Sub(bodyA.velocityAt(rA)).Dot(normal)

				// compute normal impulse
				impulse := cp.normalMass.Neg().Mul(vn.Add(restitution.Mul(cp.relativeVelocity)))

				// clamp the accumulated impulse
				// todo should this be stored?
				newImpulse := cp.normalImpulse.Add(impulse).Max(zero)
				impulse = newImpulse.Sub(cp.normalImpulse)
				cp.normalImpulse = newImpulse

				// Add the incremental impulse rather than the full impulse because this is not a sub-step
				cp.totalNormalImpulse = cp.totalNormalImpulse.Add(impulse.widen())

				// apply contact impulse
				applyContactImpulse32(&bodyA, &bodyB, constraint, rA, rB, normal.Mul(impulse))
			}
		}

		bodyA.store(stateA)
		bodyB.store(stateB)
	}
}

func storeImpulseRange32(startIndex, endIndex int, contacts []*contactSim, constraints []contactConstraint32) {
	constraints = constraints[startIndex:endIndex]
	contacts = contacts[startIndex:endIndex]

	for i := range endIndex - startIndex {
		constraint := &constraints[i]
		manifold := &contacts[i].manifold
		pointCount := manifold.PointCount

		for j := range pointCount {
			manifold.Points[j].NormalImpulse = constraint.points[j].normalImpulse.toQ()
			manifold.Points[j].TangentImpulse = constraint.points[j].tangentImpulse.toQ()
			manifold.Points[j].TotalNormalImpulse = constraint.points[j].totalNormalImpulse.toQ()
			manifold.Points[j].NormalVelocity = constraint.points[j].relativeVelocity.toQ()
		}

		manifold.RollingImpulse = constraint.rollingImpulse.toQ()
	}
}
