// Package q32gen derives the Q32 contact solver from contact_solver.go.
//
// The scalar contact solver is written once, against the contact grid types
// qc, qa, vec2c and rotc. Generate rewrites that source against the Q32
// wrappers qcw, qaw, vec2cw and rotcw, and gives every declaration of the
// file the suffix 32, so both solvers live in one package.
package q32gen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"regexp"
	"strings"
)

// Header opens the generated file.
const Header = "//go:build dbox2d_fixed\n\n// Code generated by tools/q32gen from contact_solver.go; DO NOT EDIT.\n\n"

// gridNames maps the contact grid identifiers to the Q32 wrappers.
var gridNames = map[string]string{
	"qc":           "qcw",
	"qa":           "qaw",
	"vec2c":        "vec2cw",
	"rotc":         "rotcw",
	"qcFrom":       "qcwFrom",
	"qaFrom":       "qawFrom",
	"rollingBound": "rollingBound32",
}

// Generate returns the Q32 contact solver for the source of contact_solver.go.
// The dispatch wrappers, whose names end in Task or contain Overflow, are
// left out: the caller of the Q32 path dispatches by itself.
func Generate(src []byte) ([]byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "contact_solver.go", src, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	names := make(map[string]string, len(gridNames))
	for from, to := range gridNames {
		names[from] = to
	}
	dropped := map[*ast.CommentGroup]bool{}
	var decls []ast.Decl
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if d.Recv == nil && isDispatch(d.Name.Name) {
				dropped[d.Doc] = true
				continue
			}
			if d.Recv == nil {
				names[d.Name.Name] = d.Name.Name + "32"
			}
		case *ast.GenDecl:
			for _, spec := range d.Specs {
				if ts, ok := spec.(*ast.TypeSpec); ok {
					names[ts.Name.Name] = ts.Name.Name + "32"
				}
			}
		}
		decls = append(decls, decl)
	}
	file.Decls = decls

	// The generate directive stays in the source file only.
	var comments []*ast.CommentGroup
	for _, group := range file.Comments {
		if !dropped[group] && !hasDirective(group) {
			comments = append(comments, group)
		}
	}
	file.Comments = comments

	ast.Inspect(file, func(n ast.Node) bool {
		if id, ok := n.(*ast.Ident); ok {
			if to, ok := names[id.Name]; ok {
				id.Name = to
			}
		}
		return true
	})
	renameInComments(file, names)

	var out bytes.Buffer
	out.WriteString(Header)
	if err := (&printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}).Fprint(&out, fset, file); err != nil {
		return nil, err
	}
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("q32gen: the generated source does not format: %w", err)
	}
	return formatted, nil
}

// isDispatch reports whether a function is a color or overflow dispatch
// wrapper of the scalar family.
func isDispatch(name string) bool {
	return strings.HasSuffix(name, "Task") || strings.Contains(name, "Overflow")
}

// hasDirective reports whether a comment group holds a go:generate line.
// CommentGroup.Text drops directive lines, so this reads the raw comments.
func hasDirective(group *ast.CommentGroup) bool {
	for _, c := range group.List {
		if strings.HasPrefix(c.Text, "//go:generate") {
			return true
		}
	}
	return false
}

// renameInComments applies the renames to whole words of the comments, so
// the generated doc comments name the generated declarations.
func renameInComments(file *ast.File, names map[string]string) {
	for _, group := range file.Comments {
		for _, c := range group.List {
			for from, to := range names {
				re := regexp.MustCompile(`\b` + regexp.QuoteMeta(from) + `\b`)
				c.Text = re.ReplaceAllString(c.Text, to)
			}
		}
	}
}
